### ISSUE TITLE
[BUG] Features don't work in container

### ISSUE THREAD

**Issue by gigabit942007** [gtat314/atete#1] opened 2021-05-27 11:29 UTC
As listed on Reddit i have a couple of issues with it,
![image](https://user-images.githubusercontent.com/8338004/119818165-8c00e300-bef7-11eb-90e5-e384f4cbf60b.png)

- Status is not shown at all for the apps - i did not have curl installed but i installed it and restarted everything, hasn't fixed it
- CPU average does not work
- release and kernel don't work on Ubuntu
- settings page are missing for: Search/Jokes/Metrics/Bookmarks -> i just get 404

Picture of top output:
![image](https://user-images.githubusercontent.com/8338004/119818588-12b5c000-bef8-11eb-8792-7b7393d9a20f.png)

**Comment by gigabit942007** [comment] 2021-05-27 11:42
After some refreshes i have found that CPU load % works intermitently.

**Comment by gtat314** [comment] 2021-05-27 17:39
Ok worked on this.

1. I am pretty sure I fixed the CPU issue
2. All the settings pages have not been created yet, apart from the applications section. However I updated the code so that it does not show 404 anymore.
3. I tried fixing the "release" issue but I guess I stumbled into a problem bigger that I expected.
4. I have no idea why the "kernel" button would not work. It uses the "uname" command that exists in all Linux distros
5. The applications should now show a lid, either red or green.

Risking being annoying, can you please reclone the repo, see if everything works with the updates, and then post the outcome of the following commands from within the container?:

`find /etc/ -maxdepth 1 -name '*release' -printf '%p\n' -exec cat {} \;`

`command -v uname`

**Comment by gigabit942007** [comment] 2021-05-27 20:31
Just tested and i the CPU load works... I think, it's at 0% which is more ore less correct. (Edit: It works, it just got to 4%)

The lid works, (Unless curl does not have the certificate because the app is self hosted, but that's a curl issue).

![image](https://user-images.githubusercontent.com/8338004/119892858-508c0600-bf43-11eb-8221-f3f0f20d49dc.png)

It's the least i can do for making this awesome dash :)

Here is the dash in action:
![image](https://user-images.githubusercontent.com/8338004/119892986-7a452d00-bf43-11eb-9ea2-6b731fe2c9a4.png)

**Comment by gigabit942007** [comment] 2021-05-27 20:58
Also, another probably difficult one, Syncthing for example has a password for the Dash so curl will of course fail like this:
`root@homepage:~# curl https://syncthing:8384/`
`Not Authorized`

Which in a way ... well the page is up so it refuses, but at the same time it's kinda failed because of "Not Authorized"

**Comment by gtat314** [comment] 2021-05-27 21:21
Glad it worked. About syncthing, what does this return?

`curl -i -L -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.5" -H "Cache-Control: max-age=0" -H "Connection: keep-alive" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" https://syncthing:8384/`

**Comment by gigabit942007** [comment] 2021-05-28 06:51
This is what i get:
![image](https://user-images.githubusercontent.com/8338004/119942196-36c9dd80-bf9a-11eb-96bf-c308e58fbe4e.png)

**Comment by gtat314** [comment] 2021-05-29 08:12
It should be working now

**Comment by gigabit942007** [comment] 2021-05-29 16:17
Awesome, it works! However it does something interesting now, when i add a new server, it automatically fills the optional field with "null" it just writes null instead of the link so i have to go to Edit and delete null, then it works.

**Comment by gtat314** [comment] 2021-05-29 16:41
I can't reproduce this on a clean install. What is the url you are adding? Perhaps it has to do something with the specific url

**Comment by gigabit942007** [comment] 2021-05-29 17:43
I will try it again, did a clean install with SSL and for some reason site broken :(, looks like PHP is not working right with SSL, will fix this first for the moment

**Comment by gigabit942007** [comment] 2021-05-29 18:10
Odly enough the issue with the field for optional went away, however i just have no ideea how the page refuses to work when i enable SSL...
- Edge Chromium - SSL - > works
- Edge Chromium - no SSL -> works
- Firefox - SSL -> does not work
- Firefox - no SSL -> works fine

**Comment by gtat314** [comment] 2021-05-29 18:17
If you can post the way you 've installed the SSL, I will check it out. When you say it does not work, what does it fail?

**Comment by gigabit942007** [comment] 2021-05-29 18:24
So the installation is a simple Ubuntu with nginx installed. This is how it looks with SSL enabled:
![image](https://user-images.githubusercontent.com/8338004/120080946-a7b8e480-c0c3-11eb-9884-0772b3bab3a7.png)
And how it should look:
![image](https://user-images.githubusercontent.com/8338004/120080973-c28b5900-c0c3-11eb-9b2b-dbcf51f94352.png)

The only difference between those 2 screenshots is one has a https link and the other one plain http.

Here is my nginx config for the site:
`server {
 listen 80 default_server;
 listen [::]:80 default_server;
 root /var/www/homepage.landomain;
 index index.php index.html index.htm;
 server_name homepage.landomain;
 location / {
  try_files $uri $uri/ =404;
 }
 location ~ [^/]\.php(/|$) {
  include snippets/fastcgi-php.conf;
  fastcgi_pass unix:/var/run/php/php-fpm.sock;
 }
}
server {
  listen 443 ssl;
  ssl_certificate /etc/ssl/homepage.landomain.crt;
  ssl_certificate_key /etc/ssl/homepage.landomain.key;
  root /var/www/homepage.landomain;
  index index.php index.html index.htm;
  server_name homepage.landomain www.homepage.landomain;
 location / {
  try_files $uri $uri/ =404;
 }

 location ~ [^/]\.php(/|$) {
  include snippets/fastcgi-php.conf;
  fastcgi_pass unix:/var/run/php/php-fpm.sock;
 }
}`

Please note that "landomain" is just a placeholder, it's not the actual domain used. I used to have some other page here but that worked with SSL

**Comment by gigabit942007** [comment] 2021-06-02 10:44
Update: Bit the bullet and just wiped Firefox clean and now it just works... must be some weird cache entry or something. This can be closed :)

**Comment by gtat314** [comment] 2021-06-02 10:46
Thank god. Never managed to reproduce the error you mentioned. Closing it. Thanks for all the help.

**Closed as completed by gtat314** 2021-06-02 10:46 UTC
